In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

2023-07-04 15:18:21.191519: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


TensorFlow version: 2.12.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

2023-07-04 15:19:49.211754: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:266] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-07-04 15:19:49.211782: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:168] retrieving CUDA diagnostic information for host: c75db859e6d1
2023-07-04 15:19:49.211787: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:175] hostname: c75db859e6d1
2023-07-04 15:19:49.211889: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:199] libcuda reported version is: NOT_FOUND: was unable to find libcuda.so DSO loaded into this program
2023-07-04 15:19:49.211908: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:203] kernel reported version is: 530.41.3


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

2023-07-04 11:32:14.162938: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:637] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


array([[ 0.14192337, -0.29849726,  0.08782645, -0.13386662, -0.5367067 ,
        -0.70057577, -0.08556339,  0.34479806,  0.07812828,  0.3263012 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()


array([[0.1183412 , 0.076184  , 0.11210939, 0.0898177 , 0.06003585,
        0.05096163, 0.09426267, 0.14495839, 0.1110274 , 0.14230175]],
      dtype=float32)

In [4]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)


In [7]:
loss_fn(y_train[:1], predictions).numpy()


2.9766822

In [5]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [6]:
model.fit(x_train, y_train, epochs=5)


Epoch 1/5
1875/1875 [==============================] - 2s 741us/step - loss: 0.2959 - accuracy: 0.9136
Epoch 2/5
1875/1875 [==============================] - 1s 722us/step - loss: 0.1429 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 1s 721us/step - loss: 0.1073 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 1s 716us/step - loss: 0.0882 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 1s 728us/step - loss: 0.0774 - accuracy: 0.9758


In [10]:
model.evaluate(x_test,  y_test, verbose=2)


313/313 - 0s - loss: 0.0774 - accuracy: 0.9758 - 258ms/epoch - 826us/step


[0.0774245411157608, 0.9757999777793884]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.72455117e-08, 7.33339034e-09, 9.35286516e-06, 3.50056775e-03,
        2.24797871e-11, 4.60367630e-07, 1.36167744e-11, 9.96469498e-01,
        9.62457349e-08, 2.00114337e-05],
       [7.83611220e-09, 1.25972756e-05, 9.99980092e-01, 6.48892001e-06,
        1.84342427e-15, 1.82817832e-08, 2.13961537e-09, 1.57221919e-13,
        7.99106999e-07, 1.70654316e-13],
       [8.44637427e-08, 9.99025822e-01, 7.16414652e-05, 2.25914755e-05,
        2.62617745e-04, 6.84464430e-06, 1.46774655e-05, 3.86608299e-04,
        2.07073434e-04, 2.03799482e-06],
       [9.99195516e-01, 7.65201591e-08, 9.58281234e-05, 2.86184604e-06,
        5.30577040e-07, 3.02506487e-06, 6.52851653e-04, 2.25136846e-05,
        5.68695100e-08, 2.66632469e-05],
       [5.41752934e-06, 3.68281441e-08, 1.06434763e-05, 8.99644519e-08,
        9.99026775e-01, 2.56008349e-07, 6.96521374e-06, 5.39448665e-05,
        3.95886275e-07, 8.95519974e-04]], dtype=float32)>